name: Lint VBA

on:
  push:
    branches:
      - linting
  pull_request:
jobs:
  test-and-static-analysis:
    name: Test and Static Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Lint
      uses: Vba-actions/lint-vba@dev
